//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.09 at 09:33:15 PM EEST 
//


package ru.yandex.maps.ymaps._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import net.opengis.gml.BoundedByType;
import net.opengis.gml.MetaDataPropertyType;
import net.opengis.gml.PointType;


/**
 * <p>Java class for GeoObjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeoObjectType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/gml}metaDataProperty"/>
 *         &lt;element ref="{http://www.opengis.net/gml}name"/>
 *         &lt;element ref="{http://www.opengis.net/gml}boundedBy"/>
 *         &lt;element ref="{http://www.opengis.net/gml}Point"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeoObjectType", propOrder = {
    "metaDataProperty",
    "name",
    "boundedBy",
    "point"
})
public class GeoObjectType {

    @XmlElement(namespace = "http://www.opengis.net/gml", required = true)
    protected MetaDataPropertyType metaDataProperty;
    @XmlElement(namespace = "http://www.opengis.net/gml", required = true)
    protected String name;
    @XmlElement(namespace = "http://www.opengis.net/gml", required = true)
    protected BoundedByType boundedBy;
    @XmlElement(name = "Point", namespace = "http://www.opengis.net/gml", required = true)
    protected PointType point;

    /**
     * Gets the value of the metaDataProperty property.
     * 
     * @return
     *     possible object is
     *     {@link MetaDataPropertyType }
     *     
     */
    public MetaDataPropertyType getMetaDataProperty() {
        return metaDataProperty;
    }

    /**
     * Sets the value of the metaDataProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaDataPropertyType }
     *     
     */
    public void setMetaDataProperty(MetaDataPropertyType value) {
        this.metaDataProperty = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the boundedBy property.
     * 
     * @return
     *     possible object is
     *     {@link BoundedByType }
     *     
     */
    public BoundedByType getBoundedBy() {
        return boundedBy;
    }

    /**
     * Sets the value of the boundedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BoundedByType }
     *     
     */
    public void setBoundedBy(BoundedByType value) {
        this.boundedBy = value;
    }

    /**
     * Gets the value of the point property.
     * 
     * @return
     *     possible object is
     *     {@link PointType }
     *     
     */
    public PointType getPoint() {
        return point;
    }

    /**
     * Sets the value of the point property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointType }
     *     
     */
    public void setPoint(PointType value) {
        this.point = value;
    }

    @Override
    public String toString() {
        return "GeoObjectType{" + "metaDataProperty=" + metaDataProperty + ", name='" + name + '\'' + ", boundedBy="
                + boundedBy + ", point=" + point + '}';
    }
}
