//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.09 at 09:33:15 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://maps.yandex.ru/ymaps/1.x", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.yandex.maps.ymaps._1;
