//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.09 at 09:33:15 PM EEST 
//


package ru.yandex.maps.ymaps._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ymapsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ymapsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GeoObjectCollection" type="{http://maps.yandex.ru/ymaps/1.x}GeoObjectCollectionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ymapsType", propOrder = {
    "geoObjectCollection"
})
public class YmapsType {

    @XmlElement(name = "GeoObjectCollection", required = true)
    protected GeoObjectCollectionType geoObjectCollection;

    /**
     * Gets the value of the geoObjectCollection property.
     * 
     * @return
     *     possible object is
     *     {@link GeoObjectCollectionType }
     *     
     */
    public GeoObjectCollectionType getGeoObjectCollection() {
        return geoObjectCollection;
    }

    /**
     * Sets the value of the geoObjectCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeoObjectCollectionType }
     *     
     */
    public void setGeoObjectCollection(GeoObjectCollectionType value) {
        this.geoObjectCollection = value;
    }

}
