//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.09 at 09:33:15 PM EEST 
//


package oasis.names.tc.ciq.xsdschema.xal._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ThoroughfareType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ThoroughfareType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ThoroughfareName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Premise" type="{urn:oasis:names:tc:ciq:xsdschema:xAL:2.0}PremiseType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ThoroughfareType", propOrder = {
    "thoroughfareName",
    "premise"
})
public class ThoroughfareType {

    @XmlElement(name = "ThoroughfareName", required = true)
    protected String thoroughfareName;
    @XmlElement(name = "Premise", required = true)
    protected PremiseType premise;

    /**
     * Gets the value of the thoroughfareName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThoroughfareName() {
        return thoroughfareName;
    }

    /**
     * Sets the value of the thoroughfareName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThoroughfareName(String value) {
        this.thoroughfareName = value;
    }

    /**
     * Gets the value of the premise property.
     * 
     * @return
     *     possible object is
     *     {@link PremiseType }
     *     
     */
    public PremiseType getPremise() {
        return premise;
    }

    /**
     * Sets the value of the premise property.
     * 
     * @param value
     *     allowed object is
     *     {@link PremiseType }
     *     
     */
    public void setPremise(PremiseType value) {
        this.premise = value;
    }

}
