CREATE TABLE TBL1 (
        id INT NOT NULL,
        first_name VARCHAR2(64),
        mobile VARCHAR2(30)
    )
    LOGGING;

CREATE TABLE TBL2 (
        id INT NOT NULL,
        code INT NOT NULL,
        language INT NOT NULL,
        tbl1_id INT NOT NULL,
        first_name VARCHAR2(64),
        mobile VARCHAR2(30)
    )
    LOGGING;

ALTER TABLE TBL1 ADD CONSTRAINT PK_TBL1 PRIMARY KEY (id);

ALTER TABLE TBL2 ADD CONSTRAINT PK_TBL2 PRIMARY KEY (id);

ALTER TABLE TBL2 ADD CONSTRAINT UN_TBL2_CODE_LANGUAGE UNIQUE (code, language);

ALTER TABLE TBL2 ADD CONSTRAINT FK_TBL2_TBL1 FOREIGN KEY (tbl1_id)
    REFERENCES TBL1 (id);