//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.09 at 09:33:15 PM EEST 
//


package ru.yandex.maps.geocoder._1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.yandex.maps.geocoder._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GeocoderMetaData_QNAME = new QName("http://maps.yandex.ru/geocoder/1.x", "GeocoderMetaData");
    private final static QName _GeocoderResponseMetaData_QNAME = new QName("http://maps.yandex.ru/geocoder/1.x", "GeocoderResponseMetaData");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.yandex.maps.geocoder._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GeocoderResponseMetaDataType }
     * 
     */
    public GeocoderResponseMetaDataType createGeocoderResponseMetaDataType() {
        return new GeocoderResponseMetaDataType();
    }

    /**
     * Create an instance of {@link GeocoderMetaDataType }
     * 
     */
    public GeocoderMetaDataType createGeocoderMetaDataType() {
        return new GeocoderMetaDataType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeocoderMetaDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://maps.yandex.ru/geocoder/1.x", name = "GeocoderMetaData")
    public JAXBElement<GeocoderMetaDataType> createGeocoderMetaData(GeocoderMetaDataType value) {
        return new JAXBElement<GeocoderMetaDataType>(_GeocoderMetaData_QNAME, GeocoderMetaDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeocoderResponseMetaDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://maps.yandex.ru/geocoder/1.x", name = "GeocoderResponseMetaData")
    public JAXBElement<GeocoderResponseMetaDataType> createGeocoderResponseMetaData(GeocoderResponseMetaDataType value) {
        return new JAXBElement<GeocoderResponseMetaDataType>(_GeocoderResponseMetaData_QNAME, GeocoderResponseMetaDataType.class, null, value);
    }

}
