//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.09 at 09:33:15 PM EEST 
//


package net.opengis.gml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ru.yandex.maps.ymaps._1.GeoObjectType;


/**
 * <p>Java class for featureMemberType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="featureMemberType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://maps.yandex.ru/ymaps/1.x}GeoObject"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "featureMemberType", propOrder = {
    "geoObject"
})
public class FeatureMemberType {

    @XmlElement(name = "GeoObject", namespace = "http://maps.yandex.ru/ymaps/1.x", required = true)
    protected GeoObjectType geoObject;

    /**
     * Gets the value of the geoObject property.
     * 
     * @return
     *     possible object is
     *     {@link GeoObjectType }
     *     
     */
    public GeoObjectType getGeoObject() {
        return geoObject;
    }

    /**
     * Sets the value of the geoObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeoObjectType }
     *     
     */
    public void setGeoObject(GeoObjectType value) {
        this.geoObject = value;
    }

}
