//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.09 at 09:33:15 PM EEST 
//


package net.opengis.gml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ru.yandex.maps.geocoder._1.GeocoderMetaDataType;
import ru.yandex.maps.geocoder._1.GeocoderResponseMetaDataType;


/**
 * <p>Java class for metaDataPropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="metaDataPropertyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://maps.yandex.ru/geocoder/1.x}GeocoderResponseMetaData" minOccurs="0"/>
 *         &lt;element ref="{http://maps.yandex.ru/geocoder/1.x}GeocoderMetaData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "metaDataPropertyType", propOrder = {
    "geocoderResponseMetaData",
    "geocoderMetaData"
})
public class MetaDataPropertyType {

    @XmlElement(name = "GeocoderResponseMetaData", namespace = "http://maps.yandex.ru/geocoder/1.x")
    protected GeocoderResponseMetaDataType geocoderResponseMetaData;
    @XmlElement(name = "GeocoderMetaData", namespace = "http://maps.yandex.ru/geocoder/1.x")
    protected GeocoderMetaDataType geocoderMetaData;

    /**
     * Gets the value of the geocoderResponseMetaData property.
     * 
     * @return
     *     possible object is
     *     {@link GeocoderResponseMetaDataType }
     *     
     */
    public GeocoderResponseMetaDataType getGeocoderResponseMetaData() {
        return geocoderResponseMetaData;
    }

    /**
     * Sets the value of the geocoderResponseMetaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeocoderResponseMetaDataType }
     *     
     */
    public void setGeocoderResponseMetaData(GeocoderResponseMetaDataType value) {
        this.geocoderResponseMetaData = value;
    }

    /**
     * Gets the value of the geocoderMetaData property.
     * 
     * @return
     *     possible object is
     *     {@link GeocoderMetaDataType }
     *     
     */
    public GeocoderMetaDataType getGeocoderMetaData() {
        return geocoderMetaData;
    }

    /**
     * Sets the value of the geocoderMetaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeocoderMetaDataType }
     *     
     */
    public void setGeocoderMetaData(GeocoderMetaDataType value) {
        this.geocoderMetaData = value;
    }

    @Override
    public String toString() {
        return "MetaDataPropertyType{" + "geocoderResponseMetaData=" + geocoderResponseMetaData + ", geocoderMetaData="
                + geocoderMetaData + '}';
    }
}
